<h2>Click en el ICONO para copiar el NOMBRE!</h2>
<div id="yummy-24">
    <ul id="icons-24" class="clearfix">
        <li class="mws-i-24 copied i-abacus" title="i-abacus"></li>
        <li class="mws-i-24 copied i-acces-denied-sign" title="i-acces-denied-sign"></li>
        <li class="mws-i-24 copied i-address-book-1" title="i-address-book-1"></li>
        <li class="mws-i-24 copied i-address-book-2" title="i-address-book-2"></li>
        <li class="mws-i-24 copied i-address-book-3" title="i-address-book-3"></li>
        <li class="mws-i-24 copied i-address-book-4" title="i-address-book-4"></li>
        <li class="mws-i-24 copied i-address-book-5" title="i-address-book-5"></li>
        <li class="mws-i-24 copied i-address-book" title="i-address-book"></li>
        <li class="mws-i-24 copied i-adidas-sport-shirt" title="i-adidas-sport-shirt"></li>
        <li class="mws-i-24 copied i-admin-user-2" title="i-admin-user-2"></li>
        <li class="mws-i-24 copied i-admin-user" title="i-admin-user"></li>
        <li class="mws-i-24 copied i-airplane" title="i-airplane"></li>
        <li class="mws-i-24 copied i-alarm-bell-2" title="i-alarm-bell-2"></li>
        <li class="mws-i-24 copied i-alarm-bell" title="i-alarm-bell"></li>
        <li class="mws-i-24 copied i-alarm-clock" title="i-alarm-clock"></li>
        <li class="mws-i-24 copied i-alert-2" title="i-alert-2"></li>
        <li class="mws-i-24 copied i-alert" title="i-alert"></li>
        <li class="mws-i-24 copied i-american-express" title="i-american-express"></li>
        <li class="mws-i-24 copied i-android" title="i-android"></li>
        <li class="mws-i-24 copied i-apartment-building" title="i-apartment-building"></li>
        <li class="mws-i-24 copied i-applications" title="i-applications"></li>
        <li class="mws-i-24 copied i-archive" title="i-archive"></li>
        <li class="mws-i-24 copied i-arrow-down" title="i-arrow-down"></li>
        <li class="mws-i-24 copied i-arrow-left" title="i-arrow-left"></li>
        <li class="mws-i-24 copied i-arrow-right" title="i-arrow-right"></li>
        <li class="mws-i-24 copied i-arrow-up" title="i-arrow-up"></li>
        <li class="mws-i-24 copied i-bag-2" title="i-bag-2"></li>
        <li class="mws-i-24 copied i-bag" title="i-bag"></li>
        <li class="mws-i-24 copied i-balloons" title="i-balloons"></li>
        <li class="mws-i-24 copied i-bandaid" title="i-bandaid"></li>
        <li class="mws-i-24 copied i-bar-graph" title="i-bar-graph"></li>
        <li class="mws-i-24 copied i-battery-almost-empty" title="i-battery-almost-empty"></li>
        <li class="mws-i-24 copied i-battery-almost-full" title="i-battery-almost-full"></li>
        <li class="mws-i-24 copied i-battery-empty" title="i-battery-empty"></li>
        <li class="mws-i-24 copied i-battery-full" title="i-battery-full"></li>
        <li class="mws-i-24 copied i-battery" title="i-battery"></li>
        <li class="mws-i-24 copied i-bended-arrow-down" title="i-bended-arrow-down"></li>
        <li class="mws-i-24 copied i-bended-arrow-left" title="i-bended-arrow-left"></li>
        <li class="mws-i-24 copied i-bended-arrow-right" title="i-bended-arrow-right"></li>
        <li class="mws-i-24 copied i-bended-arrow-up" title="i-bended-arrow-up"></li>
        <li class="mws-i-24 copied i-big-brush" title="i-big-brush"></li>
        <li class="mws-i-24 copied i-bills-stack" title="i-bills-stack"></li>
        <li class="mws-i-24 copied i-blackberry-2" title="i-blackberry-2"></li>
        <li class="mws-i-24 copied i-blackberry-3" title="i-blackberry-3"></li>
        <li class="mws-i-24 copied i-blackberry" title="i-blackberry"></li>
        <li class="mws-i-24 copied i-blocks-images" title="i-blocks-images"></li>
        <li class="mws-i-24 copied i-blu-ray" title="i-blu-ray"></li>
        <li class="mws-i-24 copied i-bluetooth-2" title="i-bluetooth-2"></li>
        <li class="mws-i-24 copied i-bluetooth" title="i-bluetooth"></li>
        <li class="mws-i-24 copied i-book-bookmark" title="i-book-bookmark"></li>
        <li class="mws-i-24 copied i-book-large" title="i-book-large"></li>
        <li class="mws-i-24 copied i-book" title="i-book"></li>
        <li class="mws-i-24 copied i-bookmark" title="i-bookmark"></li>
        <li class="mws-i-24 copied i-books-2" title="i-books-2"></li>
        <li class="mws-i-24 copied i-books" title="i-books"></li>
        <li class="mws-i-24 copied i-box-incoming-2" title="i-box-incoming-2"></li>
        <li class="mws-i-24 copied i-box-incoming" title="i-box-incoming"></li>
        <li class="mws-i-24 copied i-box-outgoing-2" title="i-box-outgoing-2"></li>
        <li class="mws-i-24 copied i-box-outgoing" title="i-box-outgoing"></li>
        <li class="mws-i-24 copied i-bulls-eye" title="i-bulls-eye"></li>
        <li class="mws-i-24 copied i-calculator" title="i-calculator"></li>
        <li class="mws-i-24 copied i-calendar-today" title="i-calendar-today"></li>
        <li class="mws-i-24 copied i-camera-2" title="i-camera-2"></li>
        <li class="mws-i-24 copied i-camera" title="i-camera"></li>
        <li class="mws-i-24 copied i-candy-cane" title="i-candy-cane"></li>
        <li class="mws-i-24 copied i-car" title="i-car"></li>
        <li class="mws-i-24 copied i-cash-register" title="i-cash-register"></li>
        <li class="mws-i-24 copied i-cassette" title="i-cassette"></li>
        <li class="mws-i-24 copied i-cat" title="i-cat"></li>
        <li class="mws-i-24 copied i-cd" title="i-cd"></li>
        <li class="mws-i-24 copied i-cell-phone-reception" title="i-cell-phone-reception"></li>
        <li class="mws-i-24 copied i-chair" title="i-chair"></li>
        <li class="mws-i-24 copied i-chart-2" title="i-chart-2"></li>
        <li class="mws-i-24 copied i-chart-3" title="i-chart-3"></li>
        <li class="mws-i-24 copied i-chart-4" title="i-chart-4"></li>
        <li class="mws-i-24 copied i-chart-5" title="i-chart-5"></li>
        <li class="mws-i-24 copied i-chart-6" title="i-chart-6"></li>
        <li class="mws-i-24 copied i-chart-7" title="i-chart-7"></li>
        <li class="mws-i-24 copied i-chart-8" title="i-chart-8"></li>
        <li class="mws-i-24 copied i-chart" title="i-chart"></li>
        <li class="mws-i-24 copied i-check" title="i-check"></li>
        <li class="mws-i-24 copied i-chemical" title="i-chemical"></li>
        <li class="mws-i-24 copied i-chrome" title="i-chrome"></li>
        <li class="mws-i-24 copied i-clapboard" title="i-clapboard"></li>
        <li class="mws-i-24 copied i-clipboard-1" title="i-clipboard-1"></li>
        <li class="mws-i-24 copied i-clipboard" title="i-clipboard"></li>
        <li class="mws-i-24 copied i-clock-1" title="i-clock-1"></li>
        <li class="mws-i-24 copied i-clock-2" title="i-clock-2"></li>
        <li class="mws-i-24 copied i-clock" title="i-clock"></li>
        <li class="mws-i-24 copied i-cloud-download" title="i-cloud-download"></li>
        <li class="mws-i-24 copied i-cloud-lightning-rain" title="i-cloud-lightning-rain"></li>
        <li class="mws-i-24 copied i-cloud-lightning" title="i-cloud-lightning"></li>
        <li class="mws-i-24 copied i-cloud-rain-shining-sun" title="i-cloud-rain-shining-sun"></li>
        <li class="mws-i-24 copied i-cloud-rain-sun" title="i-cloud-rain-sun"></li>
        <li class="mws-i-24 copied i-cloud-upload" title="i-cloud-upload"></li>
        <li class="mws-i-24 copied i-cloud" title="i-cloud"></li>
        <li class="mws-i-24 copied i-cog-2" title="i-cog-2"></li>
        <li class="mws-i-24 copied i-cog-3" title="i-cog-3"></li>
        <li class="mws-i-24 copied i-cog-4" title="i-cog-4"></li>
        <li class="mws-i-24 copied i-cog-5" title="i-cog-5"></li>
        <li class="mws-i-24 copied i-cog" title="i-cog"></li>
        <li class="mws-i-24 copied i-companies" title="i-companies"></li>
        <li class="mws-i-24 copied i-computer-imac" title="i-computer-imac"></li>
        <li class="mws-i-24 copied i-coverflow" title="i-coverflow"></li>
        <li class="mws-i-24 copied i-create" title="i-create"></li>
        <li class="mws-i-24 copied i-creditcard" title="i-creditcard"></li>
        <li class="mws-i-24 copied i-cross" title="i-cross"></li>
        <li class="mws-i-24 copied i-crosshair" title="i-crosshair"></li>
        <li class="mws-i-24 copied i-cup" title="i-cup"></li>
        <li class="mws-i-24 copied i-cut-scissors" title="i-cut-scissors"></li>
        <li class="mws-i-24 copied i-cut" title="i-cut"></li>
        <li class="mws-i-24 copied i-day-calendar" title="i-day-calendar"></li>
        <li class="mws-i-24 copied i-delicious" title="i-delicious"></li>
        <li class="mws-i-24 copied i-digg-2" title="i-digg-2"></li>
        <li class="mws-i-24 copied i-digg-3" title="i-digg-3"></li>
        <li class="mws-i-24 copied i-digg-4" title="i-digg-4"></li>
        <li class="mws-i-24 copied i-digg" title="i-digg"></li>
        <li class="mws-i-24 copied i-document-1" title="i-document-1"></li>
        <li class="mws-i-24 copied i-document" title="i-document"></li>
        <li class="mws-i-24 copied i-documents-1" title="i-documents-1"></li>
        <li class="mws-i-24 copied i-documents" title="i-documents"></li>
        <li class="mws-i-24 copied i-dog-tag" title="i-dog-tag"></li>
        <li class="mws-i-24 copied i-dog-tags" title="i-dog-tags"></li>
        <li class="mws-i-24 copied i-download-to-computer" title="i-download-to-computer"></li>
        <li class="mws-i-24 copied i-download" title="i-download"></li>
        <li class="mws-i-24 copied i-dress" title="i-dress"></li>
        <li class="mws-i-24 copied i-dribbble-2" title="i-dribbble-2"></li>
        <li class="mws-i-24 copied i-dribbble-3" title="i-dribbble-3"></li>
        <li class="mws-i-24 copied i-dribbble-4" title="i-dribbble-4"></li>
        <li class="mws-i-24 copied i-dribbble" title="i-dribbble"></li>
        <li class="mws-i-24 copied i-dropbox" title="i-dropbox"></li>
        <li class="mws-i-24 copied i-drupal" title="i-drupal"></li>
        <li class="mws-i-24 copied i-dvd" title="i-dvd"></li>
        <li class="mws-i-24 copied i-eject" title="i-eject"></li>
        <li class="mws-i-24 copied i-electricity-input-2" title="i-electricity-input-2"></li>
        <li class="mws-i-24 copied i-electricity-input-plug" title="i-electricity-input-plug"></li>
        <li class="mws-i-24 copied i-electricity-input" title="i-electricity-input"></li>
        <li class="mws-i-24 copied i-electricity-plug" title="i-electricity-plug"></li>
        <li class="mws-i-24 copied i-excel-document" title="i-excel-document"></li>
        <li class="mws-i-24 copied i-excel-documents-1" title="i-excel-documents-1"></li>
        <li class="mws-i-24 copied i-excel-documents" title="i-excel-documents"></li>
        <li class="mws-i-24 copied i-exit" title="i-exit"></li>
        <li class="mws-i-24 copied i-expose" title="i-expose"></li>
        <li class="mws-i-24 copied i-expression-engine" title="i-expression-engine"></li>
        <li class="mws-i-24 copied i-eyedropper" title="i-eyedropper"></li>
        <li class="mws-i-24 copied i-facebook-1" title="i-facebook-1"></li>
        <li class="mws-i-24 copied i-facebook-like" title="i-facebook-like"></li>
        <li class="mws-i-24 copied i-facebook" title="i-facebook"></li>
        <li class="mws-i-24 copied i-favorite" title="i-favorite"></li>
        <li class="mws-i-24 copied i-female-contour" title="i-female-contour"></li>
        <li class="mws-i-24 copied i-female-symbol" title="i-female-symbol"></li>
        <li class="mws-i-24 copied i-file-cabinet" title="i-file-cabinet"></li>
        <li class="mws-i-24 copied i-film-2" title="i-film-2"></li>
        <li class="mws-i-24 copied i-film-camera-2" title="i-film-camera-2"></li>
        <li class="mws-i-24 copied i-film-camera" title="i-film-camera"></li>
        <li class="mws-i-24 copied i-film-strip" title="i-film-strip"></li>
        <li class="mws-i-24 copied i-film" title="i-film"></li>
        <li class="mws-i-24 copied i-finish-banner" title="i-finish-banner"></li>
        <li class="mws-i-24 copied i-finish-flag" title="i-finish-flag"></li>
        <li class="mws-i-24 copied i-firefox" title="i-firefox"></li>
        <li class="mws-i-24 copied i-flag-2" title="i-flag-2"></li>
        <li class="mws-i-24 copied i-flag" title="i-flag"></li>
        <li class="mws-i-24 copied i-flatscreen" title="i-flatscreen"></li>
        <li class="mws-i-24 copied i-flip-clock" title="i-flip-clock"></li>
        <li class="mws-i-24 copied i-folder-1" title="i-folder-1"></li>
        <li class="mws-i-24 copied i-folder" title="i-folder"></li>
        <li class="mws-i-24 copied i-footprint" title="i-footprint"></li>
        <li class="mws-i-24 copied i-footprints" title="i-footprints"></li>
        <li class="mws-i-24 copied i-fountain-pen" title="i-fountain-pen"></li>
        <li class="mws-i-24 copied i-frames" title="i-frames"></li>
        <li class="mws-i-24 copied i-g-key" title="i-g-key"></li>
        <li class="mws-i-24 copied i-glass" title="i-glass"></li>
        <li class="mws-i-24 copied i-globe-2" title="i-globe-2"></li>
        <li class="mws-i-24 copied i-globe" title="i-globe"></li>
        <li class="mws-i-24 copied i-go-back-from-screen-1" title="i-go-back-from-screen-1"></li>
        <li class="mws-i-24 copied i-go-back-from-screen" title="i-go-back-from-screen"></li>
        <li class="mws-i-24 copied i-go-full-screen" title="i-go-full-screen"></li>
        <li class="mws-i-24 copied i-google-buzz" title="i-google-buzz"></li>
        <li class="mws-i-24 copied i-google-maps" title="i-google-maps"></li>
        <li class="mws-i-24 copied i-graph-2" title="i-graph-2"></li>
        <li class="mws-i-24 copied i-graph" title="i-graph"></li>
        <li class="mws-i-24 copied i-group-2" title="i-group-2"></li>
        <li class="mws-i-24 copied i-group" title="i-group"></li>
        <li class="mws-i-24 copied i-halloween-pumpkin" title="i-halloween-pumpkin"></li>
        <li class="mws-i-24 copied i-hard-disk" title="i-hard-disk"></li>
        <li class="mws-i-24 copied i-hd-2" title="i-hd-2"></li>
        <li class="mws-i-24 copied i-hd-3" title="i-hd-3"></li>
        <li class="mws-i-24 copied i-hd" title="i-hd"></li>
        <li class="mws-i-24 copied i-headphones" title="i-headphones"></li>
        <li class="mws-i-24 copied i-heart-favorite" title="i-heart-favorite"></li>
        <li class="mws-i-24 copied i-help" title="i-help"></li>
        <li class="mws-i-24 copied i-home-1" title="i-home-1"></li>
        <li class="mws-i-24 copied i-home-2" title="i-home-2"></li>
        <li class="mws-i-24 copied i-home" title="i-home"></li>
        <li class="mws-i-24 copied i-hour-glass" title="i-hour-glass"></li>
        <li class="mws-i-24 copied i-ice-cream-2" title="i-ice-cream-2"></li>
        <li class="mws-i-24 copied i-ice-cream" title="i-ice-cream"></li>
        <li class="mws-i-24 copied i-ichat" title="i-ichat"></li>
        <li class="mws-i-24 copied i-ideal" title="i-ideal"></li>
        <li class="mws-i-24 copied i-image-2" title="i-image-2"></li>
        <li class="mws-i-24 copied i-image" title="i-image"></li>
        <li class="mws-i-24 copied i-images-2" title="i-images-2"></li>
        <li class="mws-i-24 copied i-images" title="i-images"></li>
        <li class="mws-i-24 copied i-inbox" title="i-inbox"></li>
        <li class="mws-i-24 copied i-info-about" title="i-info-about"></li>
        <li class="mws-i-24 copied i-ipad-2" title="i-ipad-2"></li>
        <li class="mws-i-24 copied i-ipad" title="i-ipad"></li>
        <li class="mws-i-24 copied i-iphone-3g" title="i-iphone-3g"></li>
        <li class="mws-i-24 copied i-iphone-4-2" title="i-iphone-4-2"></li>
        <li class="mws-i-24 copied i-iphone-4" title="i-iphone-4"></li>
        <li class="mws-i-24 copied i-ipod-classic" title="i-ipod-classic"></li>
        <li class="mws-i-24 copied i-ipod-nano-2" title="i-ipod-nano-2"></li>
        <li class="mws-i-24 copied i-ipod-nano" title="i-ipod-nano"></li>
        <li class="mws-i-24 copied i-ipod-shuffle" title="i-ipod-shuffle"></li>
        <li class="mws-i-24 copied i-joomla" title="i-joomla"></li>
        <li class="mws-i-24 copied i-key-2" title="i-key-2"></li>
        <li class="mws-i-24 copied i-key" title="i-key"></li>
        <li class="mws-i-24 copied i-keyboard" title="i-keyboard"></li>
        <li class="mws-i-24 copied i-ladys-purse" title="i-ladys-purse"></li>
        <li class="mws-i-24 copied i-lamp" title="i-lamp"></li>
        <li class="mws-i-24 copied i-laptop" title="i-laptop"></li>
        <li class="mws-i-24 copied i-lastfm-2" title="i-lastfm-2"></li>
        <li class="mws-i-24 copied i-lastfm" title="i-lastfm"></li>
        <li class="mws-i-24 copied i-leaf" title="i-leaf"></li>
        <li class="mws-i-24 copied i-lemonade-stand-2" title="i-lemonade-stand-2"></li>
        <li class="mws-i-24 copied i-lemonade-stand" title="i-lemonade-stand"></li>
        <li class="mws-i-24 copied i-light-bulb" title="i-light-bulb"></li>
        <li class="mws-i-24 copied i-link-2" title="i-link-2"></li>
        <li class="mws-i-24 copied i-link" title="i-link"></li>
        <li class="mws-i-24 copied i-linux" title="i-linux"></li>
        <li class="mws-i-24 copied i-list-image" title="i-list-image"></li>
        <li class="mws-i-24 copied i-list-images" title="i-list-images"></li>
        <li class="mws-i-24 copied i-list" title="i-list"></li>
        <li class="mws-i-24 copied i-loading-bar" title="i-loading-bar"></li>
        <li class="mws-i-24 copied i-lock-locked" title="i-lock-locked"></li>
        <li class="mws-i-24 copied i-locked-2" title="i-locked-2"></li>
        <li class="mws-i-24 copied i-locked-folder" title="i-locked-folder"></li>
        <li class="mws-i-24 copied i-locked" title="i-locked"></li>
        <li class="mws-i-24 copied i-looking-glass" title="i-looking-glass"></li>
        <li class="mws-i-24 copied i-macos" title="i-macos"></li>
        <li class="mws-i-24 copied i-magic-mouse" title="i-magic-mouse"></li>
        <li class="mws-i-24 copied i-magnifying-glass-2" title="i-magnifying-glass-2"></li>
        <li class="mws-i-24 copied i-magnifying-glass" title="i-magnifying-glass"></li>
        <li class="mws-i-24 copied i-mail-2" title="i-mail-2"></li>
        <li class="mws-i-24 copied i-mail" title="i-mail"></li>
        <li class="mws-i-24 copied i-male-contour" title="i-male-contour"></li>
        <li class="mws-i-24 copied i-male-symbol" title="i-male-symbol"></li>
        <li class="mws-i-24 copied i-map" title="i-map"></li>
        <li class="mws-i-24 copied i-marker" title="i-marker"></li>
        <li class="mws-i-24 copied i-mastercard" title="i-mastercard"></li>
        <li class="mws-i-24 copied i-medical-case" title="i-medical-case"></li>
        <li class="mws-i-24 copied i-megaphone" title="i-megaphone"></li>
        <li class="mws-i-24 copied i-message" title="i-message"></li>
        <li class="mws-i-24 copied i-mickey" title="i-mickey"></li>
        <li class="mws-i-24 copied i-microphone" title="i-microphone"></li>
        <li class="mws-i-24 copied i-mighty-mouse" title="i-mighty-mouse"></li>
        <li class="mws-i-24 copied i-minus" title="i-minus"></li>
        <li class="mws-i-24 copied i-mobile-phone-2" title="i-mobile-phone-2"></li>
        <li class="mws-i-24 copied i-mobile-phone" title="i-mobile-phone"></li>
        <li class="mws-i-24 copied i-mobypicture" title="i-mobypicture"></li>
        <li class="mws-i-24 copied i-money-2" title="i-money-2"></li>
        <li class="mws-i-24 copied i-money" title="i-money"></li>
        <li class="mws-i-24 copied i-monitor" title="i-monitor"></li>
        <li class="mws-i-24 copied i-month-calendar" title="i-month-calendar"></li>
        <li class="mws-i-24 copied i-mouse-" title="i-mouse-"></li>
        <li class="mws-i-24 copied i-mouse-2" title="i-mouse-2"></li>
        <li class="mws-i-24 copied i-mouseires" title="i-mouseires"></li>
        <li class="mws-i-24 copied i-multiple-users" title="i-multiple-users"></li>
        <li class="mws-i-24 copied i-music-folder" title="i-music-folder"></li>
        <li class="mws-i-24 copied i-music" title="i-music"></li>
        <li class="mws-i-24 copied i-musical-keyboard" title="i-musical-keyboard"></li>
        <li class="mws-i-24 copied i-myspace-2" title="i-myspace-2"></li>
        <li class="mws-i-24 copied i-myspace" title="i-myspace"></li>
        <li class="mws-i-24 copied i-new-message" title="i-new-message"></li>
        <li class="mws-i-24 copied i-next-track" title="i-next-track"></li>
        <li class="mws-i-24 copied i-nike-sport-shirt" title="i-nike-sport-shirt"></li>
        <li class="mws-i-24 copied i-note-book" title="i-note-book"></li>
        <li class="mws-i-24 copied i-off" title="i-off"></li>
        <li class="mws-i-24 copied i-old-phone" title="i-old-phone"></li>
        <li class="mws-i-24 copied i-pacman-ghost" title="i-pacman-ghost"></li>
        <li class="mws-i-24 copied i-pacman" title="i-pacman"></li>
        <li class="mws-i-24 copied i-paint-brush" title="i-paint-brush"></li>
        <li class="mws-i-24 copied i-pants" title="i-pants"></li>
        <li class="mws-i-24 copied i-paperclip" title="i-paperclip"></li>
        <li class="mws-i-24 copied i-paypal-2" title="i-paypal-2"></li>
        <li class="mws-i-24 copied i-paypal-3" title="i-paypal-3"></li>
        <li class="mws-i-24 copied i-paypal-4" title="i-paypal-4"></li>
        <li class="mws-i-24 copied i-paypal-5" title="i-paypal-5"></li>
        <li class="mws-i-24 copied i-paypal" title="i-paypal"></li>
        <li class="mws-i-24 copied i-pdf-document" title="i-pdf-document"></li>
        <li class="mws-i-24 copied i-pdf-documents-1" title="i-pdf-documents-1"></li>
        <li class="mws-i-24 copied i-pdf-documents" title="i-pdf-documents"></li>
        <li class="mws-i-24 copied i-pencil-edit" title="i-pencil-edit"></li>
        <li class="mws-i-24 copied i-pencil" title="i-pencil"></li>
        <li class="mws-i-24 copied i-personal-folder-user-folder" title="i-personal-folder-user-folder"></li>
        <li class="mws-i-24 copied i-phone-2" title="i-phone-2"></li>
        <li class="mws-i-24 copied i-phone-3" title="i-phone-3"></li>
        <li class="mws-i-24 copied i-phone-4" title="i-phone-4"></li>
        <li class="mws-i-24 copied i-phone-hook" title="i-phone-hook"></li>
        <li class="mws-i-24 copied i-phone" title="i-phone"></li>
        <li class="mws-i-24 copied i-piggy-bank" title="i-piggy-bank"></li>
        <li class="mws-i-24 copied i-plane-suitcase" title="i-plane-suitcase"></li>
        <li class="mws-i-24 copied i-plate-diner" title="i-plate-diner"></li>
        <li class="mws-i-24 copied i-play" title="i-play"></li>
        <li class="mws-i-24 copied i-plixi" title="i-plixi"></li>
        <li class="mws-i-24 copied i-plus" title="i-plus"></li>
        <li class="mws-i-24 copied i-polaroids" title="i-polaroids"></li>
        <li class="mws-i-24 copied i-post-card" title="i-post-card"></li>
        <li class="mws-i-24 copied i-power" title="i-power"></li>
        <li class="mws-i-24 copied i-powerpoint-document" title="i-powerpoint-document"></li>
        <li class="mws-i-24 copied i-powerpoint-documents-1" title="i-powerpoint-documents-1"></li>
        <li class="mws-i-24 copied i-powerpoint-documents" title="i-powerpoint-documents"></li>
        <li class="mws-i-24 copied i-presentation-1" title="i-presentation-1"></li>
        <li class="mws-i-24 copied i-presentation" title="i-presentation"></li>
        <li class="mws-i-24 copied i-preview" title="i-preview"></li>
        <li class="mws-i-24 copied i-previous-track" title="i-previous-track"></li>
        <li class="mws-i-24 copied i-price-tag" title="i-price-tag"></li>
        <li class="mws-i-24 copied i-price-tags" title="i-price-tags"></li>
        <li class="mws-i-24 copied i-printer" title="i-printer"></li>
        <li class="mws-i-24 copied i-quicktime-new" title="i-quicktime-new"></li>
        <li class="mws-i-24 copied i-quicktime" title="i-quicktime"></li>
        <li class="mws-i-24 copied i-radio-signal" title="i-radio-signal"></li>
        <li class="mws-i-24 copied i-radio" title="i-radio"></li>
        <li class="mws-i-24 copied i-rake-and-scoop" title="i-rake-and-scoop"></li>
        <li class="mws-i-24 copied i-record" title="i-record"></li>
        <li class="mws-i-24 copied i-recycle-symbol" title="i-recycle-symbol"></li>
        <li class="mws-i-24 copied i-recycled-bag" title="i-recycled-bag"></li>
        <li class="mws-i-24 copied i-refresh-2" title="i-refresh-2"></li>
        <li class="mws-i-24 copied i-refresh-3" title="i-refresh-3"></li>
        <li class="mws-i-24 copied i-refresh-4" title="i-refresh-4"></li>
        <li class="mws-i-24 copied i-refresh" title="i-refresh"></li>
        <li class="mws-i-24 copied i-repeat" title="i-repeat"></li>
        <li class="mws-i-24 copied i-robot" title="i-robot"></li>
        <li class="mws-i-24 copied i-rss" title="i-rss"></li>
        <li class="mws-i-24 copied i-ruler-2" title="i-ruler-2"></li>
        <li class="mws-i-24 copied i-ruler" title="i-ruler"></li>
        <li class="mws-i-24 copied i-running-man" title="i-running-man"></li>
        <li class="mws-i-24 copied i-safari" title="i-safari"></li>
        <li class="mws-i-24 copied i-save" title="i-save"></li>
        <li class="mws-i-24 copied i-scan-label-2" title="i-scan-label-2"></li>
        <li class="mws-i-24 copied i-scan-label-3" title="i-scan-label-3"></li>
        <li class="mws-i-24 copied i-scan-label" title="i-scan-label"></li>
        <li class="mws-i-24 copied i-sd-2" title="i-sd-2"></li>
        <li class="mws-i-24 copied i-sd-3" title="i-sd-3"></li>
        <li class="mws-i-24 copied i-sd" title="i-sd"></li>
        <li class="mws-i-24 copied i-settings-1" title="i-settings-1"></li>
        <li class="mws-i-24 copied i-settings-2" title="i-settings-2"></li>
        <li class="mws-i-24 copied i-settings" title="i-settings"></li>
        <li class="mws-i-24 copied i-shades" title="i-shades"></li>
        <li class="mws-i-24 copied i-shopping-bag" title="i-shopping-bag"></li>
        <li class="mws-i-24 copied i-shopping-basket-2" title="i-shopping-basket-2"></li>
        <li class="mws-i-24 copied i-shopping-basket" title="i-shopping-basket"></li>
        <li class="mws-i-24 copied i-shopping-cart-2" title="i-shopping-cart-2"></li>
        <li class="mws-i-24 copied i-shopping-cart-3" title="i-shopping-cart-3"></li>
        <li class="mws-i-24 copied i-shopping-cart-4" title="i-shopping-cart-4"></li>
        <li class="mws-i-24 copied i-shopping-cart" title="i-shopping-cart"></li>
        <li class="mws-i-24 copied i-shuffle" title="i-shuffle"></li>
        <li class="mws-i-24 copied i-sign-post-2" title="i-sign-post-2"></li>
        <li class="mws-i-24 copied i-sign-post" title="i-sign-post"></li>
        <li class="mws-i-24 copied i-single-document" title="i-single-document"></li>
        <li class="mws-i-24 copied i-single-excel-document" title="i-single-excel-document"></li>
        <li class="mws-i-24 copied i-single-pdf-document" title="i-single-pdf-document"></li>
        <li class="mws-i-24 copied i-single-powerpoint-document" title="i-single-powerpoint-document"></li>
        <li class="mws-i-24 copied i-single-user" title="i-single-user"></li>
        <li class="mws-i-24 copied i-single-word-document" title="i-single-word-document"></li>
        <li class="mws-i-24 copied i-single-zip-document" title="i-single-zip-document"></li>
        <li class="mws-i-24 copied i-skype-2" title="i-skype-2"></li>
        <li class="mws-i-24 copied i-skype" title="i-skype"></li>
        <li class="mws-i-24 copied i-sleeveless-shirt" title="i-sleeveless-shirt"></li>
        <li class="mws-i-24 copied i-small-brush" title="i-small-brush"></li>
        <li class="mws-i-24 copied i-socks" title="i-socks"></li>
        <li class="mws-i-24 copied i-sound" title="i-sound"></li>
        <li class="mws-i-24 copied i-speech-bubble-2" title="i-speech-bubble-2"></li>
        <li class="mws-i-24 copied i-speech-bubble" title="i-speech-bubble"></li>
        <li class="mws-i-24 copied i-speech-bubbles-1" title="i-speech-bubbles-1"></li>
        <li class="mws-i-24 copied i-speech-bubbles-2" title="i-speech-bubbles-2"></li>
        <li class="mws-i-24 copied i-speech-bubbles" title="i-speech-bubbles"></li>
        <li class="mws-i-24 copied i-sport-shirt" title="i-sport-shirt"></li>
        <li class="mws-i-24 copied i-sticky-note" title="i-sticky-note"></li>
        <li class="mws-i-24 copied i-stop" title="i-stop"></li>
        <li class="mws-i-24 copied i-stopatch" title="i-stopatch"></li>
        <li class="mws-i-24 copied i-strategy-2" title="i-strategy-2"></li>
        <li class="mws-i-24 copied i-strategy" title="i-strategy"></li>
        <li class="mws-i-24 copied i-strike-through-month-calendar" title="i-strike-through-month-calendar"></li>
        <li class="mws-i-24 copied i-stubleupon" title="i-stubleupon"></li>
        <li class="mws-i-24 copied i-suitcase-1" title="i-suitcase-1"></li>
        <li class="mws-i-24 copied i-suitcase-2" title="i-suitcase-2"></li>
        <li class="mws-i-24 copied i-sweater" title="i-sweater"></li>
        <li class="mws-i-24 copied i-t-shirt" title="i-t-shirt"></li>
        <li class="mws-i-24 copied i-table-1" title="i-table-1"></li>
        <li class="mws-i-24 copied i-table" title="i-table"></li>
        <li class="mws-i-24 copied i-tag-1" title="i-tag-1"></li>
        <li class="mws-i-24 copied i-tag" title="i-tag"></li>
        <li class="mws-i-24 copied i-tags-2" title="i-tags-2"></li>
        <li class="mws-i-24 copied i-television" title="i-television"></li>
        <li class="mws-i-24 copied i-text-document" title="i-text-document"></li>
        <li class="mws-i-24 copied i-text-documents" title="i-text-documents"></li>
        <li class="mws-i-24 copied i-text-styling-2" title="i-text-styling-2"></li>
        <li class="mws-i-24 copied i-text-styling-3" title="i-text-styling-3"></li>
        <li class="mws-i-24 copied i-text-styling" title="i-text-styling"></li>
        <li class="mws-i-24 copied i-timer" title="i-timer"></li>
        <li class="mws-i-24 copied i-tools" title="i-tools"></li>
        <li class="mws-i-24 copied i-traffic-light" title="i-traffic-light"></li>
        <li class="mws-i-24 copied i-trashcan-2" title="i-trashcan-2"></li>
        <li class="mws-i-24 copied i-trashcan" title="i-trashcan"></li>
        <li class="mws-i-24 copied i-travel-suitcase" title="i-travel-suitcase"></li>
        <li class="mws-i-24 copied i-tree" title="i-tree"></li>
        <li class="mws-i-24 copied i-trolly" title="i-trolly"></li>
        <li class="mws-i-24 copied i-truck-2" title="i-truck-2"></li>
        <li class="mws-i-24 copied i-truck" title="i-truck"></li>
        <li class="mws-i-24 copied i-tumbler" title="i-tumbler"></li>
        <li class="mws-i-24 copied i-twitter-1" title="i-twitter-1"></li>
        <li class="mws-i-24 copied i-twitter-2" title="i-twitter-2"></li>
        <li class="mws-i-24 copied i-twitter" title="i-twitter"></li>
        <li class="mws-i-24 copied i-umbrella" title="i-umbrella"></li>
        <li class="mws-i-24 copied i-under-construction" title="i-under-construction"></li>
        <li class="mws-i-24 copied i-unfavorite" title="i-unfavorite"></li>
        <li class="mws-i-24 copied i-universal-acces" title="i-universal-acces"></li>
        <li class="mws-i-24 copied i-unlock-unlocked" title="i-unlock-unlocked"></li>
        <li class="mws-i-24 copied i-unlocked" title="i-unlocked"></li>
        <li class="mws-i-24 copied i-upload" title="i-upload"></li>
        <li class="mws-i-24 copied i-usb-stick" title="i-usb-stick"></li>
        <li class="mws-i-24 copied i-user-2" title="i-user-2"></li>
        <li class="mws-i-24 copied i-user-comment" title="i-user-comment"></li>
        <li class="mws-i-24 copied i-user" title="i-user"></li>
        <li class="mws-i-24 copied i-users-2" title="i-users-2"></li>
        <li class="mws-i-24 copied i-users" title="i-users"></li>
        <li class="mws-i-24 copied i-v-card-1" title="i-v-card-1"></li>
        <li class="mws-i-24 copied i-v-card-2" title="i-v-card-2"></li>
        <li class="mws-i-24 copied i-v-card-3" title="i-v-card-3"></li>
        <li class="mws-i-24 copied i-v-card" title="i-v-card"></li>
        <li class="mws-i-24 copied i-vault" title="i-vault"></li>
        <li class="mws-i-24 copied i-vimeo-2" title="i-vimeo-2"></li>
        <li class="mws-i-24 copied i-vimeo-3" title="i-vimeo-3"></li>
        <li class="mws-i-24 copied i-vimeo-4" title="i-vimeo-4"></li>
        <li class="mws-i-24 copied i-vimeo-5" title="i-vimeo-5"></li>
        <li class="mws-i-24 copied i-vimeo" title="i-vimeo"></li>
        <li class="mws-i-24 copied i-visa-2" title="i-visa-2"></li>
        <li class="mws-i-24 copied i-visa" title="i-visa"></li>
        <li class="mws-i-24 copied i-wacom-2" title="i-wacom-2"></li>
        <li class="mws-i-24 copied i-wacom" title="i-wacom"></li>
        <li class="mws-i-24 copied i-walking-man" title="i-walking-man"></li>
        <li class="mws-i-24 copied i-wifi-2" title="i-wifi-2"></li>
        <li class="mws-i-24 copied i-wifi-signal-2" title="i-wifi-signal-2"></li>
        <li class="mws-i-24 copied i-wifi-signal" title="i-wifi-signal"></li>
        <li class="mws-i-24 copied i-wifi" title="i-wifi"></li>
        <li class="mws-i-24 copied i-windows" title="i-windows"></li>
        <li class="mws-i-24 copied i-wine-glass" title="i-wine-glass"></li>
        <li class="mws-i-24 copied i-winner-podium" title="i-winner-podium"></li>
        <li class="mws-i-24 copied i-word-document" title="i-word-document"></li>
        <li class="mws-i-24 copied i-word-documents-1" title="i-word-documents-1"></li>
        <li class="mws-i-24 copied i-word-documents" title="i-word-documents"></li>
        <li class="mws-i-24 copied i-wordpress-2" title="i-wordpress-2"></li>
        <li class="mws-i-24 copied i-wordpress" title="i-wordpress"></li>
        <li class="mws-i-24 copied i-youtube-2" title="i-youtube-2"></li>
        <li class="mws-i-24 copied i-youtube-3" title="i-youtube-3"></li>
        <li class="mws-i-24 copied i-youtube-4" title="i-youtube-4"></li>
        <li class="mws-i-24 copied i-youtube" title="i-youtube"></li>
        <li class="mws-i-24 copied i-zip-documents" title="i-zip-documents"></li>
        <li class="mws-i-24 copied i-zip-file" title="i-zip-file"></li>
        <li class="mws-i-24 copied i-zip-files" title="i-zip-files"></li>
    </ul>
</div>
<script>
    $(document).ready(function(){
        $(".copied").click(function (){
            new Clipboard('.copied', {
                text: function(trigger) {
                    return trigger.getAttribute('title');
                }
            });
            alert("Copiado!")
        });
    });
</script>
